### ISSUE TITLE
support python3

### ISSUE THREAD

**Issue by nixawk** [nixawk/nmap_vscan#2]
```
01:24 $ ipy
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from nmap_vscan import vscan

In [2]: nmap = vscan.ServiceScan('nmap-service-probes')

In [3]: nmap.scan('www.apache.org', 80, "tcp")
ERROR:nmap_vscan.vscan:www.apache.org : 80 - must be str, not bytes
Traceback (most recent call last):
  File "/Users/unix/Projects/nmap_vscan/nmap_vscan/vscan.py", line 420, in send_tcp_request
    data += _
TypeError: must be str, not bytes
ERROR:nmap_vscan.vscan:www.apache.org : 80 - must be str, not bytes
Traceback (most recent call last):
  File "/Users/unix/Projects/nmap_vscan/nmap_vscan/vscan.py", line 420, in send_tcp_request
    data += _
TypeError: must be str, not bytes
ERROR:nmap_vscan.vscan:www.apache.org : 80 - must be str, not bytes
Traceback (most recent call last):
  File "/Users/unix/Projects/nmap_vscan/nmap_vscan/vscan.py", line 420, in send_tcp_request
    data += _
TypeError: must be str, not bytes
ERROR:nmap_vscan.vscan:www.apache.org : 80 - must be str, not bytes
Traceback (most recent call last):
  File "/Users/unix/Projects/nmap_vscan/nmap_vscan/vscan.py", line 420, in send_tcp_request
    data += _
TypeError: must be str, not bytes
```

**Comment by thapr0digy** [comment]
Is this project dead? Would love to see Python3 support as well.

**Comment by 5z1punch** [comment]
Any updates?

**Comment by nixawk** [comment]
I'll try it later.

**Comment by apanly** [comment]
> I'll try it later.

change Line 420

`data += str(_, encoding="utf-8") `

OK , support python3

**Comment by hamza-saeedCys** [comment]
try with these lines: (remove while loop)
                _ = client.recv(SOCKET_READ_BUFFERSIZE)
                _ = _.decode('utf-8')
                if not _:
                           return
                data+= _
